"""first migrate

Revision ID: f13811987dfb
Revises: 
Create Date: 2019-02-10 17:27:11.231726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13811987dfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('pred15', sa.Float(), nullable=True),
    sa.Column('pred30', sa.Float(), nullable=True),
    sa.Column('pred60', sa.Float(), nullable=True),
    sa.Column('pred120', sa.Float(), nullable=True),
    sa.Column('pred240', sa.Float(), nullable=True),
    sa.Column('pred480', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('dateTime')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emailHash', sa.String(length=32), nullable=True),
    sa.Column('apiKey', sa.String(length=16), nullable=True),
    sa.Column('dateJoined', sa.DateTime(), nullable=True),
    sa.Column('timeOfLastRequest', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_apiKey'), 'user', ['apiKey'], unique=True)
    op.create_index(op.f('ix_user_emailHash'), 'user', ['emailHash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_emailHash'), table_name='user')
    op.drop_index(op.f('ix_user_apiKey'), table_name='user')
    op.drop_table('user')
    op.drop_table('prediction')
    # ### end Alembic commands ###
